/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptop;

/**
 *
 * @author Mochamad Riza Syarif
 */
public class deteksimonitor1 extends javax.swing.JFrame {

    /**
     * Creates new form deteksimonitor1
     */
    public deteksimonitor1() {
        initComponents();
    }
    
    public static String jeniskerusakan ="";
    public static String penyebabkerusakan ="";
    public static String saranusul ="";
    public static String judul ="Monitor";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1360, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("DETEKSI KERUSAKAN PADA MONITOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Apakah Monitor Laptop Anda Mengalami :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("DETEKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 115, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 115, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Retak / Pecah", "Bergaris", "Seluruh layar hitam atau gelap (Blank)", "Flicker (Berbayang)", "Goomy (Bercak Putih bersinar lebih terang)", "Dead Pixel (terdapat titik-titik kecil)", "Layar redup atau berubah warna secara keseluruhan", "Muncul kotak-kotak di seluruh layar", "komposisi / Proporsi Warna suatu objek tidak sesuai", "\"adanya 1 keanehan bentuk objek atau Muncul objek gambar yang tidak dikenal\"", "Resolusi Gambar tidak Proporsi dengan ukuran layar" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 540, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Monitor1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blue.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               judul ="MONITOR";
      
if ( jComboBox1.getSelectedItem() == "Retak / Pecah"){ jeniskerusakan ="LCD"; penyebabkerusakan ="Benturan benda keras"; saranusul ="Mengganti LCD"; }
if ( jComboBox1.getSelectedItem() == "Bergaris"){ jeniskerusakan ="LCD"; penyebabkerusakan ="LCD Rusak"; saranusul ="Mengganti LCD"; }
if ( jComboBox1.getSelectedItem() == "Seluruh layar hitam atau gelap (Blank)"){ jeniskerusakan ="LCD"; penyebabkerusakan ="Kabel + konektor kotor & renggang"; saranusul ="Membersihkan konektor kabel data LCD"; }
if ( jComboBox1.getSelectedItem() == "Flicker (Berbayang)"){ jeniskerusakan ="LCD"; penyebabkerusakan ="Kabel + konektor kotor & renggang"; saranusul ="Membersihkan konektor kabel data LCD"; }
if ( jComboBox1.getSelectedItem() == "Goomy (Bercak Putih bersinar lebih terang)"){ jeniskerusakan ="LCD"; penyebabkerusakan ="LCD Rusak"; saranusul ="Mengganti LCD"; }
if ( jComboBox1.getSelectedItem() == "Dead Pixel (terdapat titik-titik kecil)"){ jeniskerusakan ="LCD"; penyebabkerusakan ="LCD Rusak"; saranusul ="Mengganti LCD"; }
if ( jComboBox1.getSelectedItem() == "Layar redup atau berubah warna secara keseluruhan"){ jeniskerusakan ="LCD"; penyebabkerusakan ="Kabel + konektor kotor & renggang"; saranusul ="Membersihkan konektor kabel data LCD"; }
if ( jComboBox1.getSelectedItem() == "Muncul kotak-kotak di seluruh layar"){ jeniskerusakan ="Card VGA"; penyebabkerusakan ="Kondisi laptop panas yang berlebihan"; saranusul ="Saat pengoperasian laptop hindari beralaskas menggunakan benda yang menghambat sirkulasi udara seperti beralaskan kasur, karpet, bantal, selimut dan semisalnya"; }
if ( jComboBox1.getSelectedItem() == "komposisi / Proporsi Warna suatu objek tidak sesuai"){ jeniskerusakan ="Card VGA"; penyebabkerusakan ="Slot AGP pada module / Card VGA rusak"; saranusul ="Mengganti Card VGA"; }
if ( jComboBox1.getSelectedItem() == "adanya 1 keanehan bentuk objek atau Muncul objek gambar yang tidak dikenal"){ jeniskerusakan ="Card VGA"; penyebabkerusakan ="Slot PCI-E pada module / Card VGA rusak"; saranusul ="Mengganti Card VGA"; }
if ( jComboBox1.getSelectedItem() == ""){ jeniskerusakan =""; penyebabkerusakan =""; saranusul =""; }
if ( jComboBox1.getSelectedItem() == "Resolusi Gambar tidak Proporsi dengan ukuran layar"){ jeniskerusakan ="Card VGA"; penyebabkerusakan ="(1) Driver VGA rusak atau corrupt dikarenakan virus/n(2) Ketidakcocokan driver VGA dengan Spesifikasi Laptop/natau Sistem Operasi (mungkin user melakukan install ulang OS)"; saranusul ="(1) Uninstall Driver Video & Graphic yang saat ini anda gunakan/n(2) Install Driver Video & Graphic yang sesuai dengan spesifikasi laptop anda"; }


        
        new kerusakanmonitor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deteksimonitor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deteksimonitor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deteksimonitor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deteksimonitor1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deteksimonitor1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
