/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptop;



/**
 *
 * @author Mochamad Riza Syarif
 */
public class power extends javax.swing.JFrame {

    /**
     * Creates new form keyboard
     */
    public power() {
        initComponents();
    }
    
    public static String jeniskerusakan ="";
    public static String penyebabkerusakan ="";
    public static String saranusul ="";
    public static String judul ="Power";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("DETEKSI KERUSAKAN PADA DAYA POWER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Indikator pengisian daya mati dan laptop tidak terisi daya", "Indikator pengisian daya hidup tetapi laptop tidak terisi daya", "PLN ON, indikator pengisian daya mati tetapi laptop mengisi daya", "PLN ON, Indikator power mati dan laptop tidak terisi daya", "PLN ON, Indikator daya hidup dan laptop tidak terisi daya" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(jComboBox1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 568, 30));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("DETEKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 129, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 129, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Apakah Daya Power Laptop Anda Mengalami :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laptop.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 310));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blue.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
judul = "POWER";

if ( jComboBox1.getSelectedItem() == "Indikator pengisian daya mati dan laptop tidak terisi daya"){ jeniskerusakan ="Tidak Ada Daya / Arus Listrik"; penyebabkerusakan ="(1) PLN OFF / mati listrik \n  (2) Adaptor charger rusak \n (3) Kabel adaptor charger putus"; saranusul = "(1) Pastikan listrik di rumah anda hidup / normal \n (2) Ganti kabel power (AC) /n (3) Ganti adaptor charger sesuai spesifikasi laptop anda"; }


if ( jComboBox1.getSelectedItem() == "Indikator pengisian daya hidup tetapi laptop tidak terisi  daya"){ jeniskerusakan ="Tidak Ada Daya / Arus Listrik"; penyebabkerusakan ="(1) Indikator LED power rusak \n (2) PLN OFF / mati listrik \n (3) Adaptor charger rusak \n (4) Kabel adaptor charger putus"; saranusul = "(1) Ganti LED Indikator Daya /n (2) Pastikan listrik di rumah anda hidup / normal /n (3) Ganti kabel power (AC) /n (4) Ganti adaptor charger sesuai spesifikasi laptop anda"; }



if ( jComboBox1.getSelectedItem() == "PLN ON, indikator pengisian daya mati tetapi laptop mengisi daya"){ jeniskerusakan ="Indikator LED Daya"; penyebabkerusakan ="Indikator LED power rusak "; saranusul = "Ganti LED Indikator Daya"; }


if ( jComboBox1.getSelectedItem() == "PLN ON, Indikator power mati dan laptop tidak terisi daya"){ jeniskerusakan ="Kabel atau Adaptor Charger"; penyebabkerusakan ="(1) Adaptor charger rusak \n (2) Kabel adaptor charger putus"; saranusul = "(1) Ganti kabel power (AC) /n (2) Ganti adaptor charger sesuai spesifikasi laptop anda"; }

if ( jComboBox1.getSelectedItem() == "PLN ON, Indikator daya hidup dan laptop tidak terisi daya"){ jeniskerusakan ="Indikator LED atau Blok Sistem Daya Laptop"; penyebabkerusakan ="(1) Indikator LED power rusak  \n (2) Blok Power pada Motherboard rusak"; saranusul = "(1) Ganti LED Indikator Daya /n (2) Ganti atau Perbaiki Blok Rangkaian Daya / Power yang terdapat pada Motherboard"; }



new kerusakanpower().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(power.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new power().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
