/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptop;

/**
 *
 * @author Mochamad Riza Syarif
 */
public class solv_usb extends javax.swing.JFrame {

    /**
     * Creates new form deteksimonitor1
     */
    public solv_usb() {
        initComponents();
    }
    
    public static String jeniskerusakan ="";
    public static String penyebabkerusakan ="";
    public static String saranusul ="";
    public static String judul ="USB DRIVER";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("DETEKSI KERUSAKAN PADA USB");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Apakah USB Laptop Anda Mengalami :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setText("DETEKSI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 115, 40));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 115, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Perangkat (device) tidak terdeteksi atau tidak berfungsi ketika dikoneksikan ke Port USB laptop. Dan bila devices tersebut dikoneksikan ke laptop lain pun juga sama, devices tidak terdeteksi dan tidak berfungsi", "Perangkat (device) tidak terdeteksi atau tidak berfungsi ketika dikoneksikan ke Port USB laptop tetapi bila device dikoneksikan ke port USB laptop lain devices terdeteksi dan berfungsi", "Perangkat atau devices terdeteksi di laptop namun tidak berfungsi atau tidak dapat read/write data pada devices tersebut", " ", " ", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 1180, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/blue.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               judul ="USB DRIVER";
      
if ( jComboBox1.getSelectedItem() == "Perangkat (device) tidak terdeteksi atau tidak berfungsi ketika dikoneksikan ke Port USB laptop. Dan bila devices tersebut dikoneksikan ke laptop lain pun juga sama, devices tidak terdeteksi dan tidak berfungsi"){ jeniskerusakan ="Kabel Data atau Perangkat"; penyebabkerusakan ="(1) Perangkat (device) rusak\n(2) Kabel data device putus\n(3) Driver USB rusak (error) atau belum dinstall"; saranusul = "(1) Pastikan kondisi fisik perangkat yang dihubungkan ke laptop dalam keadaan baik\n(2) Ganti kabel data USB\n(3) Uninstall-Install Driver Interface USB sesuai spesifikasi laptop anda"; }
if ( jComboBox1.getSelectedItem() == "Perangkat (device) tidak terdeteksi atau tidak berfungsi ketika dikoneksikan ke Port USB laptop tetapi bila device dikoneksikan ke port USB laptop lain devices terdeteksi dan berfungsi"){ jeniskerusakan ="Driver USB atau Port Interface USB"; penyebabkerusakan ="(1) Driver USB rusak (error) atau belum dinstall\n(2) Konektor atau Port Interface USB laptop tersebut rusak"; saranusul = "(1) Ganti kabel data USB\n(2) Uninstall-Install Driver Interface USB sesuai spesifikasi laptop anda"; }
if ( jComboBox1.getSelectedItem() == "Perangkat atau devices terdeteksi di laptop namun tidak berfungsi atau tidak dapat read/write data pada devices tersebut"){ jeniskerusakan ="Driver USB atau Perangkat Terkena Virus"; penyebabkerusakan ="(1) Driver USB error / rusak\n(2) Perangkat (device) terkena virus"; saranusul = "(1) Uninstall-Install Driver Interface USB sesuai spesifkasi laptop anda\n(2) Scan Virus pada perangkat tersebut"; }
  
        new kerusakanusb().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solv_usb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solv_usb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solv_usb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solv_usb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new solv_usb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
